---
- name: create user
  hosts: centos
  become: yes
  vars_prompt: 
    - name: username
      prompt: "Enter username"
      private: no
    - name: password
      prompt: "Enter password"
      private: yes

  tasks:
    - name: create user
      ansible.builtin.user: 
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present 